valor = int(input('digite um valor: '))
tab1 = print(f'{valor} x 1 = {valor * 1}')
tab2 = print(f'{valor} x 2 = {valor * 2}')
tab3 = print(f'{valor} x 3 = {valor * 3}')
tab4 = print(f'{valor} x 4 = {valor * 4}')
tab5 = print(f'{valor} x 5 = {valor * 5}')
tab6 = print(f'{valor} x 6 = {valor * 6}')
tab7 = print(f'{valor} x 7 = {valor * 7}')
tab8 = print(f'{valor} x 8 = {valor * 8}')
tab9 = print(f'{valor} x 9 = {valor * 9}')
print(tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9)

