n1 = input('digite algo: ')
print(f'o valor primitivo desse valor é : {type(n1)}')
print(f'é um numero? {n1.isnumeric()}')
print(f'é alfabetico? {n1.isalpha()}')
print(f'é alfanumerico? {n1.isalnum()}')
print(f'é em maiusculas? {n1.isupper()}')
print(f'é em minusculas? {n1.islower()}')
print(f'esta capitalizada? {n1.istitle()}')